# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain Axum dependencies with cargo
  - package-ecosystem: "cargo "
    directory: "/server"
    schedule:
      interval: "weekly"
      
  # Maintain Yew dependencies with cargo
  - package-ecosystem: "cargo "
    directory: "/yew_front"
    schedule:
      interval: "weekly"

  # Maintain Svelte/Vite dependencies with npm
  - package-ecosystem: "npm"
    directory: "/svelte_front"
    schedule:
      interval: "weekly"
