indent_style = "block"
hard_tabs = true
tab_spaces = 3
reorder_imports = true
imports_granularity = "Crate"
group_imports = "One"
max_width = 120
comment_width = 120
wrap_comments = true
format_code_in_doc_comments = true
fn_single_line = true